// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Base64Controller from "./base64_controller"
application.register("base64", Base64Controller)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import Html2hamlController from "./html2haml_controller"
application.register("html2haml", Html2hamlController)
